import turtle as trtl
trtl.speed(0)
trtl.penup()
trtl.goto(-380, 0)
trtl.pendown()
for i in range(76):
  trtl.penup()
  trtl.forward(10)
  trtl.pendown()
  trtl.right(90)
  trtl.forward(10)
  trtl.right(180)
  trtl.forward(20)
  trtl.right(180)
  trtl.forward(10)
  trtl.left(90)
trtl.penup()
trtl.goto(0, 0)
trtl.right(90)
trtl.forward(380)
trtl.right(180)
trtl.pendown()
for i in range(76):
  trtl.penup()
  trtl.forward(10)
  trtl.pendown()
  trtl.right(90)
  trtl.forward(10)
  trtl.right(180)
  trtl.forward(20)
  trtl.right(180)
  trtl.forward(10)
  trtl.left(90)
trtl.penup()
trtl.goto(-385, 0)
trtl.right(90)
trtl.pendown()
trtl.forward(775)
trtl.penup()
trtl.goto(0, -385)
trtl.pendown()
trtl.right(-90)
trtl.forward(775)
trtl.penup()
trtl.goto(-385, 0)
trtl.pendown()
trtl.setheading(220)
trtl.backward(10)
trtl.goto(-385, 0)
trtl.setheading(135)
trtl.forward(-20)
 
trtl.wn = trtl.Screen()
trtl.wn.mainloop()
 
#y=mx+b

